version: '3'
services:
  user_service:
    build: ./userService
    container_name: user_service
    ports:
      - "8000:8000"
    env_file:
      - ./userService/env-vars.env
    links:
      - user_mongo:database
    networks: 
      - backend
  user_mongo:
    image: mongo:latest
    container_name: user_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./userService/data:/data/db
    networks: 
      - backend
networks:
  backend:
    driver: 'bridge'
