version: '3'
services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - web-vars.env
    links:
      - mongodb:database
    networks: 
      - backend
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks: 
      - backend
networks:
  backend:
    driver: 'bridge'
